name: Windows CI

on: [push, pull_request]

defaults:
  run:
    shell: bash
    working-directory: Code

jobs:
  windows-cicd:
    permissions:
      id-token: write
      contents: read
      attestations: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - cfg: Build & Tests
            vs: 2022
            os: windows-2022
          - cfg: Build & Tests
            vs: 2019
            os: windows-2019
          - cfg: Analyze
            vs: 2022
            os: windows-2022

    name: Windows (${{ matrix.cfg }}, VS ${{ matrix.vs }})
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Download prebuilt FBuild binary
        uses: ./.github/actions/DownloadFBuild

      - name: Configure fbuild.bff for vs2017/vs2019
        if: matrix.os != 'windows-2022'
        run: |
          'C:\Program Files (x86)\Microsoft Visual Studio\${{ matrix.vs }}\Enterprise\VC\Tools\LLVM\x64\bin\clang.exe' --version
          # Inject "#define CI_BUILD" into root configs to activate CI logic.
          sed -i -e "1i\\
          #define CI_BUILD
          " fbuild.bff Tools/FBuild/FBuildTest/Data/testcommon.bff
          # Comment all "#define USING_VS" lines and then uncomment the one we want.
          sed -i -e "
          /#define USING_VS/ s:^[^#]*://:
          /#define USING_VS${{ matrix.vs }}/ s:^[^#]*::
          " ../External/SDK/VisualStudio/VisualStudio.bff

      - name: Configure fbuild.bff for vs2022
        if: matrix.os == 'windows-2022'
        run: |
          'C:\Program Files\Microsoft Visual Studio\${{ matrix.vs }}\Enterprise\VC\Tools\LLVM\x64\bin\clang.exe' --version
          # Inject "#define CI_BUILD" into root configs to activate CI logic.
          sed -i -e "1i\\
          #define CI_BUILD
          " fbuild.bff Tools/FBuild/FBuildTest/Data/testcommon.bff
          # Comment all "#define USING_VS" lines and then uncomment the one we want.
          sed -i -e "
          /#define USING_VS/ s:^[^#]*://:
          /#define USING_VS${{ matrix.vs }}/ s:^[^#]*::
          " ../External/SDK/VisualStudio/VisualStudio.bff

      - name: Build
        if: ${{ startsWith(matrix.cfg, 'Build') }}
        run: ${FBUILD_PATH} -nostoponerror -summary All-x64{,Clang}-{Debug,Profile,Release}

      - name: Attest binaries provenance
        if: matrix.os == 'windows-2022' && matrix.cfg == 'Build & Tests'
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: |
            tmp/x64-Release/Tools/FBuild/FBuild/FBuild.exe
            tmp/x64-Release/Tools/FBuild/FBuild/FBuild.pdb
            tmp/x64-Release/Tools/FBuild/FBuildWorker/FBuildWorker.exe
            tmp/x64-Release/Tools/FBuild/FBuildWorker/FBuildWorker.pdb

      - name: Upload FASTBuild x64-Release binaries
        if: matrix.os == 'windows-2022' && matrix.cfg == 'Build & Tests'
        uses: actions/upload-artifact@v4
        with:
          name: 'FASTBuild-Windows-x64-${{ github.sha }}'
          if-no-files-found: error
          path: |
            tmp/x64-Release/Tools/FBuild/FBuild/FBuild.exe
            tmp/x64-Release/Tools/FBuild/FBuild/FBuild.pdb
            tmp/x64-Release/Tools/FBuild/FBuildWorker/FBuildWorker.exe
            tmp/x64-Release/Tools/FBuild/FBuildWorker/FBuildWorker.pdb

      - name: Tests
        # -j1 on CI nodes avoids timeouts (CI nodes have only 2 cores)
        if: ${{ matrix.cfg == 'Build & Tests' }}
        run: ${FBUILD_PATH} -nostoponerror -j1 -summary Tests

      - name: Analyze
        if: ${{ matrix.cfg == 'Analyze' }}
        run: ${FBUILD_PATH} -nostoponerror -summary All-x64-Analyze

      - name: Build (NoUnity)
        if: ${{ startsWith(matrix.cfg, 'Build') }}
        run: ${FBUILD_PATH} -nostoponerror -summary -nounity -clean All-x64{,Clang}-Debug
